# Generated by Django 5.1.4 on 2024-12-21 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('ID_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('admin_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ID_Article', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('type', models.IntegerField()),
                ('has_content', models.BooleanField(null=True)),
                ('img_cover', models.TextField(null=True)),
                ('parent_type', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('ID_Prev_Article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.article')),
            ],
        ),
        migrations.CreateModel(
            name='Article_Feedback',
            fields=[
                ('ID_Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.article')),
                ('punctuation', models.IntegerField()),
                ('comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article_Content',
            fields=[
                ('ID_Content', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('ID_Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('ID_List', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.TextField()),
                ('is_private', models.SmallIntegerField()),
                ('ID_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List_Item',
            fields=[
                ('ID_List', models.AutoField(primary_key=True, serialize=False)),
                ('ID_Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('ID_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subject', models.CharField(max_length=150, null=True)),
                ('topic', models.CharField(max_length=150, null=True)),
                ('subtopic', models.CharField(max_length=150, null=True)),
                ('ID_Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
            ],
        ),
    ]
